{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major": 8, "minor": 6, "revision": 2, "architecture": "x64", "modernui": 1},
    "classnamespace": "box",
    "rect": [100.0, 100.0, 1100.0, 750.0],
    "openinpresentation": 1,
    "boxes": [
      {"box": {"id": "obj-1", "maxclass": "inlet", "index": 1, "comment": "envelope signal 0..1", "numinlets": 0, "numoutlets": 1, "outlettype": [""], "patching_rect": [30.0, 30.0, 30.0, 30.0]}},
      {"box": {"id": "obj-3", "maxclass": "newobj", "text": "live.remote~ @normalized 1", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [30.0, 140.0, 160.0, 22.0]}},
      {"box": {"id": "obj-4", "maxclass": "live.text", "varname": "map_btn", "parameter_enable": 1, "mode": 1, "text": "Map", "texton": "Map", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [200.0, 30.0, 44.0, 20.0], "presentation": 1, "presentation_rect": [0.0, 4.0, 38.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_longname": "MapBtn", "parameter_shortname": "Map", "parameter_type": 2, "parameter_range": [0, 1], "parameter_invisible": 1}}}},
      {"box": {"id": "obj-5", "maxclass": "message", "text": "Map a parameter", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [560.0, 690.0, 150.0, 22.0], "presentation": 1, "presentation_rect": [42.0, 4.0, 86.0, 18.0]}},
      {"box": {"id": "obj-6", "maxclass": "newobj", "text": "live.thisdevice", "numinlets": 1, "numoutlets": 3, "outlettype": ["bang", "int", ""], "patching_rect": [420.0, 30.0, 90.0, 22.0]}},
      {"box": {"id": "obj-7", "maxclass": "newobj", "text": "live.path", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", ""], "patching_rect": [560.0, 110.0, 60.0, 22.0]}},
      {"box": {"id": "obj-8", "maxclass": "newobj", "text": "live.observer", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [560.0, 200.0, 84.0, 22.0]}},
      {"box": {"id": "obj-9", "maxclass": "message", "text": "property selected_parameter", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [660.0, 160.0, 170.0, 22.0]}},
      {"box": {"id": "obj-10", "maxclass": "newobj", "text": "gate", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [560.0, 280.0, 40.0, 22.0]}},
      {"box": {"id": "obj-11", "maxclass": "newobj", "text": "route id", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [560.0, 240.0, 56.0, 22.0]}},
      {"box": {"id": "obj-12", "maxclass": "newobj", "text": "route 0", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [560.0, 320.0, 52.0, 22.0]}},
      {"box": {"id": "obj-13", "maxclass": "newobj", "text": "t b b b i i i", "numinlets": 1, "numoutlets": 6, "outlettype": ["bang", "bang", "bang", "int", "int", "int"], "patching_rect": [560.0, 360.0, 100.0, 22.0]}},
      {"box": {"id": "obj-14", "maxclass": "message", "text": "id $1", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [900.0, 400.0, 44.0, 22.0]}},
      {"box": {"id": "obj-15", "maxclass": "newobj", "text": "live.object", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [700.0, 470.0, 70.0, 22.0]}},
      {"box": {"id": "obj-16", "maxclass": "newobj", "text": "i", "numinlets": 2, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [850.0, 400.0, 30.0, 22.0]}},
      {"box": {"id": "obj-17", "maxclass": "newobj", "text": "pattr TargetId @parameter_enable 1", "numinlets": 2, "numoutlets": 3, "outlettype": ["", "", ""], "patching_rect": [850.0, 440.0, 200.0, 22.0], "saved_object_attributes": {"parameter_enable": 1, "parameter_mappable": 0}, "saved_attribute_attributes": {"valueof": {"parameter_longname": "TargetId", "parameter_shortname": "TargetId", "parameter_type": 3, "parameter_invisible": 1}}}},
      {"box": {"id": "obj-18", "maxclass": "message", "text": "id $1", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [800.0, 400.0, 44.0, 22.0]}},
      {"box": {"id": "obj-19", "maxclass": "newobj", "text": "route name canonical_parent", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", ""], "patching_rect": [700.0, 510.0, 170.0, 22.0]}},
      {"box": {"id": "obj-22", "maxclass": "message", "text": "get name", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [636.0, 400.0, 58.0, 22.0]}},
      {"box": {"id": "obj-23", "maxclass": "message", "text": "get canonical_parent", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [500.0, 400.0, 130.0, 22.0]}},
      {"box": {"id": "obj-24", "maxclass": "newobj", "text": "tosymbol", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [700.0, 545.0, 60.0, 22.0]}},
      {"box": {"id": "obj-25", "maxclass": "newobj", "text": "sel 0", "numinlets": 2, "numoutlets": 2, "outlettype": ["bang", ""], "patching_rect": [200.0, 70.0, 40.0, 22.0]}},
      {"box": {"id": "obj-26", "maxclass": "newobj", "text": "t b b b", "numinlets": 1, "numoutlets": 3, "outlettype": ["bang", "bang", "bang"], "patching_rect": [200.0, 110.0, 54.0, 22.0]}},
      {"box": {"id": "obj-27", "maxclass": "newobj", "text": "t b b", "numinlets": 1, "numoutlets": 2, "outlettype": ["bang", "bang"], "patching_rect": [420.0, 70.0, 40.0, 22.0]}},
      {"box": {"id": "obj-28", "maxclass": "message", "text": "path live_set view", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [560.0, 70.0, 110.0, 22.0]}},
      {"box": {"id": "obj-29", "maxclass": "newobj", "text": "t b l", "numinlets": 1, "numoutlets": 2, "outlettype": ["bang", ""], "patching_rect": [560.0, 150.0, 40.0, 22.0]}},
      {"box": {"id": "obj-30", "maxclass": "message", "text": "set 0", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [340.0, 400.0, 40.0, 22.0]}},
      {"box": {"id": "obj-31", "maxclass": "message", "text": "0", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [390.0, 400.0, 24.0, 22.0]}},
      {"box": {"id": "obj-32", "maxclass": "newobj", "text": "route id", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [940.0, 510.0, 56.0, 22.0]}},
      {"box": {"id": "obj-33", "maxclass": "newobj", "text": "t b i", "numinlets": 1, "numoutlets": 2, "outlettype": ["bang", "int"], "patching_rect": [940.0, 545.0, 40.0, 22.0]}},
      {"box": {"id": "obj-34", "maxclass": "message", "text": "id $1", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [990.0, 580.0, 44.0, 22.0]}},
      {"box": {"id": "obj-35", "maxclass": "newobj", "text": "pak s s", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [700.0, 620.0, 54.0, 22.0]}},
      {"box": {"id": "obj-36", "maxclass": "newobj", "text": "live.object", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [940.0, 615.0, 70.0, 22.0]}},
      {"box": {"id": "obj-37", "maxclass": "message", "text": "get name", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [880.0, 580.0, 58.0, 22.0]}},
      {"box": {"id": "obj-38", "maxclass": "newobj", "text": "route name", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [940.0, 650.0, 70.0, 22.0]}},
      {"box": {"id": "obj-39", "maxclass": "newobj", "text": "tosymbol", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [860.0, 650.0, 60.0, 22.0]}},
      {"box": {"id": "obj-40", "maxclass": "newobj", "text": "sprintf symout %s > %s", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [700.0, 655.0, 140.0, 22.0]}},
      {"box": {"id": "obj-41", "maxclass": "newobj", "text": "prepend set", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [560.0, 655.0, 74.0, 22.0]}},
      {"box": {"id": "obj-42", "maxclass": "newobj", "text": "deferlow", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [420.0, 110.0, 60.0, 22.0]}},
      {"box": {"id": "obj-43", "maxclass": "newobj", "text": "t b b", "numinlets": 1, "numoutlets": 2, "outlettype": ["bang", "bang"], "patching_rect": [420.0, 150.0, 40.0, 22.0]}},
      {"box": {"id": "obj-44", "maxclass": "message", "text": "0", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [470.0, 190.0, 24.0, 22.0]}},
      {"box": {"id": "obj-45", "maxclass": "newobj", "text": "i", "numinlets": 2, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [420.0, 270.0, 30.0, 22.0]}},
      {"box": {"id": "obj-46", "maxclass": "newobj", "text": "delay 200", "numinlets": 2, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [420.0, 230.0, 66.0, 22.0]}},
      {"box": {"id": "obj-47", "maxclass": "newobj", "text": "sel 0", "numinlets": 2, "numoutlets": 2, "outlettype": ["bang", ""], "patching_rect": [420.0, 310.0, 40.0, 22.0]}},
      {"box": {"id": "obj-48", "maxclass": "newobj", "text": "change", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", ""], "patching_rect": [850.0, 480.0, 50.0, 22.0]}},
      {"box": {"id": "obj-49", "maxclass": "newobj", "text": "route 0", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [850.0, 515.0, 52.0, 22.0]}},
      {"box": {"id": "obj-50", "maxclass": "message", "text": "1", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [640.0, 545.0, 24.0, 22.0]}},
      {"box": {"id": "obj-51", "maxclass": "message", "text": "id 0", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [200.0, 150.0, 34.0, 22.0]}},
      {"box": {"id": "obj-52", "maxclass": "message", "text": "0", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [244.0, 150.0, 24.0, 22.0]}},
      {"box": {"id": "obj-53", "maxclass": "message", "text": "set Map a parameter", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [278.0, 150.0, 124.0, 22.0]}}
    ],
    "lines": [
      {"patchline": {"source": ["obj-1", 0], "destination": ["obj-3", 0]}},
      {"patchline": {"source": ["obj-4", 0], "destination": ["obj-10", 0]}},
      {"patchline": {"source": ["obj-4", 0], "destination": ["obj-25", 0]}},
      {"patchline": {"source": ["obj-25", 0], "destination": ["obj-26", 0]}},
      {"patchline": {"source": ["obj-26", 0], "destination": ["obj-51", 0]}},
      {"patchline": {"source": ["obj-26", 1], "destination": ["obj-52", 0]}},
      {"patchline": {"source": ["obj-26", 2], "destination": ["obj-53", 0]}},
      {"patchline": {"source": ["obj-51", 0], "destination": ["obj-3", 1]}},
      {"patchline": {"source": ["obj-52", 0], "destination": ["obj-16", 0]}},
      {"patchline": {"source": ["obj-53", 0], "destination": ["obj-5", 0]}},
      {"patchline": {"source": ["obj-6", 0], "destination": ["obj-27", 0]}},
      {"patchline": {"source": ["obj-27", 1], "destination": ["obj-28", 0]}},
      {"patchline": {"source": ["obj-28", 0], "destination": ["obj-7", 0]}},
      {"patchline": {"source": ["obj-7", 0], "destination": ["obj-29", 0]}},
      {"patchline": {"source": ["obj-29", 1], "destination": ["obj-8", 1]}},
      {"patchline": {"source": ["obj-29", 0], "destination": ["obj-9", 0]}},
      {"patchline": {"source": ["obj-9", 0], "destination": ["obj-8", 0]}},
      {"patchline": {"source": ["obj-8", 0], "destination": ["obj-11", 0]}},
      {"patchline": {"source": ["obj-11", 0], "destination": ["obj-10", 1]}},
      {"patchline": {"source": ["obj-10", 0], "destination": ["obj-12", 0]}},
      {"patchline": {"source": ["obj-12", 1], "destination": ["obj-13", 0]}},
      {"patchline": {"source": ["obj-13", 5], "destination": ["obj-14", 0]}},
      {"patchline": {"source": ["obj-14", 0], "destination": ["obj-15", 1]}},
      {"patchline": {"source": ["obj-13", 4], "destination": ["obj-16", 0]}},
      {"patchline": {"source": ["obj-16", 0], "destination": ["obj-17", 0]}},
      {"patchline": {"source": ["obj-13", 3], "destination": ["obj-18", 0]}},
      {"patchline": {"source": ["obj-18", 0], "destination": ["obj-3", 1]}},
      {"patchline": {"source": ["obj-13", 2], "destination": ["obj-22", 0]}},
      {"patchline": {"source": ["obj-13", 1], "destination": ["obj-23", 0]}},
      {"patchline": {"source": ["obj-13", 0], "destination": ["obj-30", 0]}},
      {"patchline": {"source": ["obj-13", 0], "destination": ["obj-31", 0]}},
      {"patchline": {"source": ["obj-30", 0], "destination": ["obj-4", 0]}},
      {"patchline": {"source": ["obj-31", 0], "destination": ["obj-10", 0]}},
      {"patchline": {"source": ["obj-22", 0], "destination": ["obj-15", 0]}},
      {"patchline": {"source": ["obj-23", 0], "destination": ["obj-15", 0]}},
      {"patchline": {"source": ["obj-15", 0], "destination": ["obj-19", 0]}},
      {"patchline": {"source": ["obj-19", 0], "destination": ["obj-24", 0]}},
      {"patchline": {"source": ["obj-19", 0], "destination": ["obj-50", 0]}},
      {"patchline": {"source": ["obj-24", 0], "destination": ["obj-35", 1]}},
      {"patchline": {"source": ["obj-19", 1], "destination": ["obj-32", 0]}},
      {"patchline": {"source": ["obj-32", 0], "destination": ["obj-33", 0]}},
      {"patchline": {"source": ["obj-33", 1], "destination": ["obj-34", 0]}},
      {"patchline": {"source": ["obj-34", 0], "destination": ["obj-36", 1]}},
      {"patchline": {"source": ["obj-33", 0], "destination": ["obj-37", 0]}},
      {"patchline": {"source": ["obj-37", 0], "destination": ["obj-36", 0]}},
      {"patchline": {"source": ["obj-36", 0], "destination": ["obj-38", 0]}},
      {"patchline": {"source": ["obj-38", 0], "destination": ["obj-39", 0]}},
      {"patchline": {"source": ["obj-39", 0], "destination": ["obj-35", 0]}},
      {"patchline": {"source": ["obj-35", 0], "destination": ["obj-40", 0]}},
      {"patchline": {"source": ["obj-40", 0], "destination": ["obj-41", 0]}},
      {"patchline": {"source": ["obj-41", 0], "destination": ["obj-5", 0]}},
      {"patchline": {"source": ["obj-27", 0], "destination": ["obj-42", 0]}},
      {"patchline": {"source": ["obj-42", 0], "destination": ["obj-43", 0]}},
      {"patchline": {"source": ["obj-43", 1], "destination": ["obj-44", 0]}},
      {"patchline": {"source": ["obj-44", 0], "destination": ["obj-45", 1]}},
      {"patchline": {"source": ["obj-43", 0], "destination": ["obj-17", 0]}},
      {"patchline": {"source": ["obj-43", 0], "destination": ["obj-46", 0]}},
      {"patchline": {"source": ["obj-46", 0], "destination": ["obj-45", 0]}},
      {"patchline": {"source": ["obj-45", 0], "destination": ["obj-47", 0]}},
      {"patchline": {"source": ["obj-47", 0], "destination": ["obj-26", 0]}},
      {"patchline": {"source": ["obj-17", 0], "destination": ["obj-48", 0]}},
      {"patchline": {"source": ["obj-48", 0], "destination": ["obj-49", 0]}},
      {"patchline": {"source": ["obj-49", 1], "destination": ["obj-13", 0]}},
      {"patchline": {"source": ["obj-50", 0], "destination": ["obj-45", 1]}}
    ]
  }
}
